# Node.js 20 사용
FROM node:20

# 작업 디렉토리 설정
WORKDIR /app

# 환경 변수 파일 복사
COPY .env.development .env

# Vue 프로젝트 의존성 설치
COPY package.json package-lock.json ./
RUN npm install

# 소스 코드 복사
COPY . .

# Vue 개발 서버 실행 (0.0.0.0:8000에서 실행)
CMD ["npm", "run", "serve", "--", "--host", "0.0.0.0", "--port", "8000"]
