# Node.js 20 사용
FROM node:20

# 작업 디렉토리 설정
WORKDIR /app

# Vue 프로젝트 기본 설정
COPY package.json package-lock.json ./
RUN npm install

# Vue 프로젝트 빌드
COPY . .
RUN npm run build

# 정적 파일 서빙
CMD ["npm", "run", "preview"]
