# Node.js 20 사용
FROM node:20

# 작업 디렉토리 설정
WORKDIR /app

# Vue 프로젝트 의존성 설치
COPY package.json package-lock.json ./

COPY .env.production .env

RUN npm install

# 소스 코드 복사
COPY . .

# Vue CLI를 전역 설치 (필요한 경우)
RUN npm install -g @vue/cli


# Vue 빌드 실행 (dist 폴더 생성)
RUN npm run build

# Express 설치
RUN npm install express

# Express 서버 실행
CMD ["node", "server.js"]
