version: "3.8"

services:
  nginx:
    build: ./nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: vue-frontend-dev   #### container_name이 nginx에서 연결할 upstream에서의 이름
    volumes:
      - ./frontend:/app
    ports:
      - "8000:8000"
    command: npm run serve

  backend:
    build:
      context: ./backend # ✅ backend 폴더를 컨텍스트로 설정
      dockerfile: Dockerfile # ✅ backend 폴더 내 Dockerfile을 사용
    container_name: fastapi-backend
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
