# Node.js 20 사용
FROM node:20

# 작업 디렉토리 설정
WORKDIR /app

# Vue 프로젝트 의존성 설치
COPY package.json package-lock.json ./
RUN npm install

# 소스 코드 복사
COPY . .

# Vue CLI를 전역 설치 (필요한 경우)
RUN npm install -g @vue/cli
RUN npm install

# 실행 명령어를 절대 경로로 지정
CMD ["npx", "vue-cli-service", "serve"]
